server:
  port: ${API_GATEWAY_PORT}
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:${EUREKA_SERVER_PORT}/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    hostname: localhost
    prefer-ip-address: true
spring:
  application:
    name: api-gateway
  config:
    import: optional:file:./docker/.env[.properties]
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: orders
          uri: lb://order-service
          predicates:
            - Path=/orders/**
          filters:
            - PrefixPath=/api/v1
        - id: products
          uri: lb://product-service
          predicates:
            - Path=/products/**
          filters:
            - PrefixPath=/api/v1
        - id: categories
          uri: lb://product-service
          predicates:
            - Path=/categories/**
          filters:
            - PrefixPath=/api/v1/products
        - id: users
          uri: lb://user-service
          predicates:
            - Path=/users/**
          filters:
            - PrefixPath=/api/v1
      default-filters: TokenRelay=
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8090/realms/pizza-microservice-realm
        registration:
          keycloak:
            provider: keycloak
            client-id: oath-client
            client-secret: hD0z32AK9EWkyfahLrYkJcXphyoDY9Lz
            authorization-grant-type: authorization_code
            scope:
                - openid
                - email
                - profile
                - roles
