server:
  port: ${EUREKA_SERVER_PORT}
spring:
  application:
    name: service-discovery
  config:
    import: optional:file:./docker/.env[.properties]
eureka:
  client:
    register-with-eureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:${EUREKA_SERVER_PORT}/eureka/
