server:
  port: 8070
spring:
  application:
    name: user-service
  config:
    import: optional:file:D:/Study/Modsen/pizza-practice/pizza-app/docker/.env[.properties]
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${USER_DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true