server:
  port: ${PRODUCT_SERVER_PORT}
spring:
  application:
    name: product-service
  config:
    import: optional:file:./docker/.env[.properties]
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${PRODUCT_DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  liquibase:
    change-log: db/changelog/db.changelog-master.yaml
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:${EUREKA_SERVER_PORT}/eureka/